# backend/routes/__init__.py

from .api.auth import bp as auth_bp
from .api.dashboard import bp as dashboard_bp
from .api.transacoes import bp as transacoes_bp, bp_api as transacoes_api_bp
from .api.metas import bp as metas_bp, bp_api as metas_api_bp
from .api.nexo import bp as nexo_bp
from .api.categorias import bp as categorias_bp
from .api.parcelamentos import bp as parcelamentos_bp, bp_api as parcelamentos_api_bp


def register_blueprints(app):
    # ── rotas web (com url_prefix) ──
    app.register_blueprint(dashboard_bp)       # / /login /cadastro /dashboard ...
    app.register_blueprint(transacoes_bp)      # /transacoes/...
    app.register_blueprint(metas_bp)           # /metas/...
    app.register_blueprint(metas_api_bp)       # /api/metas/...
    app.register_blueprint(nexo_bp)            # /nexo/...
    app.register_blueprint(categorias_bp)      # /categorias/...
    app.register_blueprint(parcelamentos_bp)   # /parcelamentos/...

    # ── rotas API mobile (sem url_prefix) ──
    app.register_blueprint(auth_bp)            # /api/login
    app.register_blueprint(transacoes_api_bp)  # /api/transacoes/...
    app.register_blueprint(parcelamentos_api_bp) # /api/parcelamentos/...
    # metas, nexo e categorias já têm bp_api embutido no bp principal